### PR TITLE
Added “HE_Conference_Mobile_Andre”  files

### PR DESCRIPTION
**Pull request by AndreiCT**
Please review, thanks -  Andrei.

### CODE REVIEW

**Comment by fkchang** [comment]
Hi Andrei:

Are you going to complete the other 2 tasks?  Thanks

**Comment by AndreiCT** [comment]
Hi Forrest - yes, text(s) and markup are coming up in a few, thanks - Andrei.

**Comment by AndreiCT** [comment]
Forrest, please let me know if anything is missing, but more details in pick_me.txt files, thank you - Andrei.

**Comment by fkchang** [comment]
Questionnaire ?

**Comment by AndreiCT** [comment]
Hi Forrest - updated - please let me know if you can't find it or if you
have any other questions or concerns, many thanks - Andrei.

On Fri, May 27, 2016 at 2:49 PM, Forrest Chang notifications@github.com
wrote:

> Questionairre ?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/hedgeyedev/Designer-Developer-Application-Exercise/pull/4#issuecomment-222225101,
> or mute the thread
> https://github.com/notifications/unsubscribe/ASiMi3qpxiw_EV-0aK18qR36ErcASyloks5qFzytgaJpZM4In3c2
> .

## 
- Andrei

**Pull request closed without merging**
