### PR TITLE
Pull request for designer-developer-application-exercise

### PR DESCRIPTION
**Pull request by vinsonkoo**

### CODE REVIEW

**Comment by fkchang** [comment]
Hi Vinson:

Thanks for your submission. did you mean to write more for the "What are you looking for in a job?"  question?  Thanks

**Comment by vinsonkoo** [comment]
Hi Forrest,

Thanks for getting back to me. I've edited my answer for that question

**Comment by vinsonkoo** [comment]
Please let me know if you are unable to see it. Thank you.

**Comment by fkchang** [comment]
got it, thanks

**Comment by fkchang** [comment]
Thanks Vinson!

**Pull request closed without merging**
